apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
subjects:
- kind: ServiceAccount
  name: my-svc
  namespace: get-services-version  # Replace with the appropriate namespace
roleRef:
  kind: ClusterRole
  name: my-role-1
  apiGroup: rbac.authorization.k8s.io
