apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: python-script
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
